### YamlMime:ManagedReference
items:
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions
  commentId: T:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions
  id: CurveLoopVisualizerExtensions
  parent: MBF.Revit.Geometry.Extensions
  children:
  - MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ViewDrafting,Autodesk.Revit.DB.Color)
  - MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  - MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop},Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  langs:
  - csharp
  - vb
  name: CurveLoopVisualizerExtensions
  nameWithType: CurveLoopVisualizerExtensions
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions
  type: Class
  source:
    href: https://github.com/MicroBIM-DevTeam/MBF.Revit.Geometry/blob/92ee7b3d952c912142fec1d83709948a7d00945f/Extensions/CurveLoopVisualizerExtensions.cs
  assemblies:
  - MBF.Revit.Geometry
  namespace: MBF.Revit.Geometry.Extensions
  summary: Provides extension methods for visualizing and creating Revit elements from <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> objects.
  remarks: >-
    This class includes methods for creating 2D visualizations of <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> objects using

    <xref href="DirectShape" data-throw-if-not-resolved="false"></xref> elements and for generating <xref href="Autodesk.Revit.DB.DetailCurve" data-throw-if-not-resolved="false"></xref> elements in drafting views. These

    methods are designed to work with the active view of a Revit document and provide optional customization, such as

    specifying outline colors.
  example: []
  syntax:
    content: >-
      [LogAspect]

      public static class CurveLoopVisualizerExtensions
    content.vb: >-
      <LogAspect>

      Public Module CurveLoopVisualizerExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  attributes:
  - type: MB.Common.Aspects.LogAspect
    ctor: MB.Common.Aspects.LogAspect.#ctor
    arguments: []
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  commentId: M:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  id: VisualizeCurveLoop2D(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  isExtensionMethod: true
  parent: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions
  langs:
  - csharp
  - vb
  name: VisualizeCurveLoop2D(CurveLoop, Document, Color)
  nameWithType: CurveLoopVisualizerExtensions.VisualizeCurveLoop2D(CurveLoop, Document, Color)
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D(Autodesk.Revit.DB.CurveLoop, Autodesk.Revit.DB.Document, Autodesk.Revit.DB.Color)
  type: Method
  source:
    href: https://github.com/MicroBIM-DevTeam/MBF.Revit.Geometry/blob/92ee7b3d952c912142fec1d83709948a7d00945f/Extensions/CurveLoopVisualizerExtensions.cs
  assemblies:
  - MBF.Revit.Geometry
  namespace: MBF.Revit.Geometry.Extensions
  summary: >-
    Visualizes a single <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> as a 2D outline using a <xref href="DirectShape" data-throw-if-not-resolved="false"></xref> element

    in the active view of the given Revit <code class="paramref">doc</code>.
  example: []
  syntax:
    content: public static MbResult<DirectShape> VisualizeCurveLoop2D(this CurveLoop curveLoop, Document doc, Color color = null)
    parameters:
    - id: curveLoop
      type: Autodesk.Revit.DB.CurveLoop
      description: The <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> to visualize.
    - id: doc
      type: Autodesk.Revit.DB.Document
      description: The current Revit document containing the active view.
    - id: color
      type: Autodesk.Revit.DB.Color
      description: Optional outline color; defaults to red if not provided.
    return:
      type: MB.Common.Utils.Result.MbResult{Autodesk.Revit.DB.DirectShape}
      description: >-
        An <xref href="MB.Common.Utils.Result.MbResult%601" data-throw-if-not-resolved="false"></xref>:

        <ul><li><b>Success:</b> Contains the created <xref href="DirectShape" data-throw-if-not-resolved="false"></xref>.</li><li><b>Failure:</b> "CurveLoop is null."</li><li><b>Failure:</b> "Document or active view is null."</li><li><b>Failure:</b> "Failed to visualize CurveLoop: [exception message]"</li></ul>
    content.vb: Public Shared Function VisualizeCurveLoop2D(curveLoop As CurveLoop, doc As Document, color As Color = Nothing) As MbResult(Of DirectShape)
  overload: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D*
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop},Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  commentId: M:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop},Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  id: VisualizeCurveLoops2D(System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop},Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Color)
  isExtensionMethod: true
  parent: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions
  langs:
  - csharp
  - vb
  name: VisualizeCurveLoops2D(IEnumerable<CurveLoop>, Document, Color)
  nameWithType: CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(IEnumerable<CurveLoop>, Document, Color)
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(System.Collections.Generic.IEnumerable<Autodesk.Revit.DB.CurveLoop>, Autodesk.Revit.DB.Document, Autodesk.Revit.DB.Color)
  type: Method
  source:
    href: https://github.com/MicroBIM-DevTeam/MBF.Revit.Geometry/blob/92ee7b3d952c912142fec1d83709948a7d00945f/Extensions/CurveLoopVisualizerExtensions.cs
  assemblies:
  - MBF.Revit.Geometry
  namespace: MBF.Revit.Geometry.Extensions
  summary: >-
    Visualizes a list of <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> objects as 2D outlines using <xref href="DirectShape" data-throw-if-not-resolved="false"></xref> elements

    in the active view of the given Revit <code class="paramref">doc</code>.
  example: []
  syntax:
    content: public static MbResult<List<DirectShape>> VisualizeCurveLoops2D(this IEnumerable<CurveLoop> curveLoops, Document doc, Color color = null)
    parameters:
    - id: curveLoops
      type: System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop}
      description: The collection of <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> instances to visualize.
    - id: doc
      type: Autodesk.Revit.DB.Document
      description: The current Revit document containing the active view.
    - id: color
      type: Autodesk.Revit.DB.Color
      description: Optional outline color; defaults to red if not provided.
    return:
      type: MB.Common.Utils.Result.MbResult{System.Collections.Generic.List{Autodesk.Revit.DB.DirectShape}}
      description: >-
        An <xref href="MB.Common.Utils.Result.MbResult%601" data-throw-if-not-resolved="false"></xref> where <code>T</code> is <xref href="System.Collections.Generic.List%601" data-throw-if-not-resolved="false"></xref>:

        <ul><li><b>Success:</b> Contains a list of created <xref href="DirectShape" data-throw-if-not-resolved="false"></xref> elements.</li><li><b>Failure:</b> "CurveLoop collection is null."</li><li><b>Failure:</b> "Document or active view is null."</li><li><b>Failure:</b> "Failed to visualize multiple CurveLoops: [exception message]"</li></ul>
    content.vb: Public Shared Function VisualizeCurveLoops2D(curveLoops As IEnumerable(Of CurveLoop), doc As Document, color As Color = Nothing) As MbResult(Of List(Of DirectShape))
  overload: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D*
  nameWithType.vb: CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(IEnumerable(Of CurveLoop), Document, Color)
  fullName.vb: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D(System.Collections.Generic.IEnumerable(Of Autodesk.Revit.DB.CurveLoop), Autodesk.Revit.DB.Document, Autodesk.Revit.DB.Color)
  name.vb: VisualizeCurveLoops2D(IEnumerable(Of CurveLoop), Document, Color)
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ViewDrafting,Autodesk.Revit.DB.Color)
  commentId: M:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ViewDrafting,Autodesk.Revit.DB.Color)
  id: CreateCurveLoopWithDetailCurves(Autodesk.Revit.DB.CurveLoop,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ViewDrafting,Autodesk.Revit.DB.Color)
  isExtensionMethod: true
  parent: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions
  langs:
  - csharp
  - vb
  name: CreateCurveLoopWithDetailCurves(CurveLoop, Document, ViewDrafting, Color)
  nameWithType: CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves(CurveLoop, Document, ViewDrafting, Color)
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves(Autodesk.Revit.DB.CurveLoop, Autodesk.Revit.DB.Document, Autodesk.Revit.DB.ViewDrafting, Autodesk.Revit.DB.Color)
  type: Method
  source:
    href: https://github.com/MicroBIM-DevTeam/MBF.Revit.Geometry/blob/92ee7b3d952c912142fec1d83709948a7d00945f/Extensions/CurveLoopVisualizerExtensions.cs
  assemblies:
  - MBF.Revit.Geometry
  namespace: MBF.Revit.Geometry.Extensions
  summary: >-
    Creates <xref href="Autodesk.Revit.DB.DetailCurve" data-throw-if-not-resolved="false"></xref> elements in a <xref href="Autodesk.Revit.DB.ViewDrafting" data-throw-if-not-resolved="false"></xref> to represent the given

    <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static MbResult<List<DetailCurve>> CreateCurveLoopWithDetailCurves(this CurveLoop curveLoop, Document doc, ViewDrafting draftingView, Color color = null)
    parameters:
    - id: curveLoop
      type: Autodesk.Revit.DB.CurveLoop
      description: The <xref href="CurveLoop" data-throw-if-not-resolved="false"></xref> to draw.
    - id: doc
      type: Autodesk.Revit.DB.Document
      description: The current Revit document.
    - id: draftingView
      type: Autodesk.Revit.DB.ViewDrafting
      description: The drafting view where detail curves will be placed.
    - id: color
      type: Autodesk.Revit.DB.Color
      description: Optional line color; defaults to red if not provided.
    return:
      type: MB.Common.Utils.Result.MbResult{System.Collections.Generic.List{Autodesk.Revit.DB.DetailCurve}}
      description: >-
        An <xref href="MB.Common.Utils.Result.MbResult%601" data-throw-if-not-resolved="false"></xref> where <code>T</code> is <xref href="System.Collections.Generic.List%601" data-throw-if-not-resolved="false"></xref>:

        <ul><li><b>Success:</b> Contains the created list of <xref href="Autodesk.Revit.DB.DetailCurve" data-throw-if-not-resolved="false"></xref> elements.</li><li><b>Failure:</b> "CurveLoop is null."</li><li><b>Failure:</b> "Document or drafting view is null."</li><li><b>Failure:</b> "Failed to create detail curves: [exception message]"</li></ul>
    content.vb: Public Shared Function CreateCurveLoopWithDetailCurves(curveLoop As CurveLoop, doc As Document, draftingView As ViewDrafting, color As Color = Nothing) As MbResult(Of List(Of DetailCurve))
  overload: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves*
references:
- uid: CurveLoop
  commentId: T:CurveLoop
  isExternal: true
- uid: DirectShape
  commentId: T:DirectShape
  isExternal: true
- uid: Autodesk.Revit.DB.DetailCurve
  commentId: T:Autodesk.Revit.DB.DetailCurve
  isExternal: true
- uid: MBF.Revit.Geometry.Extensions
  commentId: N:MBF.Revit.Geometry.Extensions
  isExternal: true
  href: MBF.html
  name: MBF.Revit.Geometry.Extensions
  nameWithType: MBF.Revit.Geometry.Extensions
  fullName: MBF.Revit.Geometry.Extensions
  spec.csharp:
  - uid: MBF
    name: MBF
    isExternal: true
    href: MBF.html
  - name: .
  - uid: MBF.Revit
    name: Revit
    isExternal: true
    href: MBF.Revit.html
  - name: .
  - uid: MBF.Revit.Geometry
    name: Geometry
    isExternal: true
    href: MBF.Revit.Geometry.html
  - name: .
  - uid: MBF.Revit.Geometry.Extensions
    name: Extensions
    isExternal: true
    href: MBF.Revit.Geometry.Extensions.html
  spec.vb:
  - uid: MBF
    name: MBF
    isExternal: true
    href: MBF.html
  - name: .
  - uid: MBF.Revit
    name: Revit
    isExternal: true
    href: MBF.Revit.html
  - name: .
  - uid: MBF.Revit.Geometry
    name: Geometry
    isExternal: true
    href: MBF.Revit.Geometry.html
  - name: .
  - uid: MBF.Revit.Geometry.Extensions
    name: Extensions
    isExternal: true
    href: MBF.Revit.Geometry.Extensions.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MB.Common.Utils.Result.MbResult`1
  commentId: T:MB.Common.Utils.Result.MbResult`1
  parent: MB.Common.Utils.Result
  isExternal: true
  href: MB.Common.Utils.Result.MbResult-1.html
  name: MbResult<T>
  nameWithType: MbResult<T>
  fullName: MB.Common.Utils.Result.MbResult<T>
  nameWithType.vb: MbResult(Of T)
  fullName.vb: MB.Common.Utils.Result.MbResult(Of T)
  name.vb: MbResult(Of T)
  spec.csharp:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
    href: MB.Common.Utils.Result.MbResult-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
    href: MB.Common.Utils.Result.MbResult-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D*
  commentId: Overload:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D
  isExternal: true
  href: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.html#MBF_Revit_Geometry_Extensions_CurveLoopVisualizerExtensions_VisualizeCurveLoop2D_Autodesk_Revit_DB_CurveLoop_Autodesk_Revit_DB_Document_Autodesk_Revit_DB_Color_
  name: VisualizeCurveLoop2D
  nameWithType: CurveLoopVisualizerExtensions.VisualizeCurveLoop2D
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoop2D
- uid: Autodesk.Revit.DB.CurveLoop
  isExternal: true
  name: CurveLoop
  nameWithType: CurveLoop
  fullName: Autodesk.Revit.DB.CurveLoop
- uid: Autodesk.Revit.DB.Document
  commentId: T:Autodesk.Revit.DB.Document
  isExternal: true
  name: Document
  nameWithType: Document
  fullName: Autodesk.Revit.DB.Document
- uid: Autodesk.Revit.DB.Color
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: Autodesk.Revit.DB.Color
- uid: MB.Common.Utils.Result.MbResult{Autodesk.Revit.DB.DirectShape}
  commentId: T:MB.Common.Utils.Result.MbResult{Autodesk.Revit.DB.DirectShape}
  parent: MB.Common.Utils.Result
  definition: MB.Common.Utils.Result.MbResult`1
  name: MbResult<DirectShape>
  nameWithType: MbResult<DirectShape>
  fullName: MB.Common.Utils.Result.MbResult<Autodesk.Revit.DB.DirectShape>
  nameWithType.vb: MbResult(Of DirectShape)
  fullName.vb: MB.Common.Utils.Result.MbResult(Of Autodesk.Revit.DB.DirectShape)
  name.vb: MbResult(Of DirectShape)
  spec.csharp:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
  - name: <
  - uid: Autodesk.Revit.DB.DirectShape
    name: DirectShape
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Autodesk.Revit.DB.DirectShape
    name: DirectShape
    isExternal: true
  - name: )
- uid: MB.Common.Utils.Result
  commentId: N:MB.Common.Utils.Result
  isExternal: true
  href: MB.html
  name: MB.Common.Utils.Result
  nameWithType: MB.Common.Utils.Result
  fullName: MB.Common.Utils.Result
  spec.csharp:
  - uid: MB
    name: MB
    isExternal: true
    href: MB.html
  - name: .
  - uid: MB.Common
    name: Common
    isExternal: true
    href: MB.Common.html
  - name: .
  - uid: MB.Common.Utils
    name: Utils
    isExternal: true
    href: MB.Common.Utils.html
  - name: .
  - uid: MB.Common.Utils.Result
    name: Result
    isExternal: true
    href: MB.Common.Utils.Result.html
  spec.vb:
  - uid: MB
    name: MB
    isExternal: true
    href: MB.html
  - name: .
  - uid: MB.Common
    name: Common
    isExternal: true
    href: MB.Common.html
  - name: .
  - uid: MB.Common.Utils
    name: Utils
    isExternal: true
    href: MB.Common.Utils.html
  - name: .
  - uid: MB.Common.Utils.Result
    name: Result
    isExternal: true
    href: MB.Common.Utils.Result.html
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D*
  commentId: Overload:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D
  isExternal: true
  href: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.html#MBF_Revit_Geometry_Extensions_CurveLoopVisualizerExtensions_VisualizeCurveLoops2D_System_Collections_Generic_IEnumerable_Autodesk_Revit_DB_CurveLoop__Autodesk_Revit_DB_Document_Autodesk_Revit_DB_Color_
  name: VisualizeCurveLoops2D
  nameWithType: CurveLoopVisualizerExtensions.VisualizeCurveLoops2D
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.VisualizeCurveLoops2D
- uid: System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop}
  commentId: T:System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.CurveLoop}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<CurveLoop>
  nameWithType: IEnumerable<CurveLoop>
  fullName: System.Collections.Generic.IEnumerable<Autodesk.Revit.DB.CurveLoop>
  nameWithType.vb: IEnumerable(Of CurveLoop)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Autodesk.Revit.DB.CurveLoop)
  name.vb: IEnumerable(Of CurveLoop)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Autodesk.Revit.DB.CurveLoop
    name: CurveLoop
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Autodesk.Revit.DB.CurveLoop
    name: CurveLoop
    isExternal: true
  - name: )
- uid: MB.Common.Utils.Result.MbResult{System.Collections.Generic.List{Autodesk.Revit.DB.DirectShape}}
  commentId: T:MB.Common.Utils.Result.MbResult{System.Collections.Generic.List{Autodesk.Revit.DB.DirectShape}}
  parent: MB.Common.Utils.Result
  definition: MB.Common.Utils.Result.MbResult`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: MbResult<List<DirectShape>>
  nameWithType: MbResult<List<DirectShape>>
  fullName: MB.Common.Utils.Result.MbResult<System.Collections.Generic.List<Autodesk.Revit.DB.DirectShape>>
  nameWithType.vb: MbResult(Of List(Of DirectShape))
  fullName.vb: MB.Common.Utils.Result.MbResult(Of System.Collections.Generic.List(Of Autodesk.Revit.DB.DirectShape))
  name.vb: MbResult(Of List(Of DirectShape))
  spec.csharp:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
  - name: <
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Autodesk.Revit.DB.DirectShape
    name: DirectShape
    isExternal: true
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Autodesk.Revit.DB.DirectShape
    name: DirectShape
    isExternal: true
  - name: )
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Autodesk.Revit.DB.ViewDrafting
  commentId: T:Autodesk.Revit.DB.ViewDrafting
  isExternal: true
  name: ViewDrafting
  nameWithType: ViewDrafting
  fullName: Autodesk.Revit.DB.ViewDrafting
- uid: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves*
  commentId: Overload:MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves
  isExternal: true
  href: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.html#MBF_Revit_Geometry_Extensions_CurveLoopVisualizerExtensions_CreateCurveLoopWithDetailCurves_Autodesk_Revit_DB_CurveLoop_Autodesk_Revit_DB_Document_Autodesk_Revit_DB_ViewDrafting_Autodesk_Revit_DB_Color_
  name: CreateCurveLoopWithDetailCurves
  nameWithType: CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves
  fullName: MBF.Revit.Geometry.Extensions.CurveLoopVisualizerExtensions.CreateCurveLoopWithDetailCurves
- uid: MB.Common.Utils.Result.MbResult{System.Collections.Generic.List{Autodesk.Revit.DB.DetailCurve}}
  commentId: T:MB.Common.Utils.Result.MbResult{System.Collections.Generic.List{Autodesk.Revit.DB.DetailCurve}}
  parent: MB.Common.Utils.Result
  definition: MB.Common.Utils.Result.MbResult`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: MbResult<List<DetailCurve>>
  nameWithType: MbResult<List<DetailCurve>>
  fullName: MB.Common.Utils.Result.MbResult<System.Collections.Generic.List<Autodesk.Revit.DB.DetailCurve>>
  nameWithType.vb: MbResult(Of List(Of DetailCurve))
  fullName.vb: MB.Common.Utils.Result.MbResult(Of System.Collections.Generic.List(Of Autodesk.Revit.DB.DetailCurve))
  name.vb: MbResult(Of List(Of DetailCurve))
  spec.csharp:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
  - name: <
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Autodesk.Revit.DB.DetailCurve
    name: DetailCurve
    isExternal: true
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: MB.Common.Utils.Result.MbResult`1
    name: MbResult
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Autodesk.Revit.DB.DetailCurve
    name: DetailCurve
    isExternal: true
  - name: )
  - name: )
shouldSkipMarkup: true
